### PR TITLE
Closes #148 Refactored Where structure to a binary tree for lazy evaluation

### LINKED ISSUE #148: Lazily evaluate WHERE clause
In order to complete #147 and fix #142, the `Where` statement needs to be lazily evaluated so that it can retain typed information that can be mutated.

### Problem

Currently, `Where` is defined as...

```kotlin
sealed class Where<out T : Field>(private val whereString: String) {
    override fun toString(): String = whereString
}
```

Any instance of it holds to the evaluated WHERE clause via the `whereString`. So, for example,

```kotlin
val emailContains = Fields.Email.Address contains "veronica"
```

At this point, the WHERE clause has already been evaluated to something like (pseudocode to keep things simple),

```kotlin
Where {
    whereString  = "address LIKE 'veronica'"
}
```

If we redact the entire `whereString`, it will evaluate to...

```kotlin
"***********************"
```

This certainly does uphold privacy laws but it doesn't help us debug the issues in production when we look at logs from crashes or analytics. Furthermore, this will just produce an exception when executing the query 😓 

Then comes the question, how do we maintain the WHERE clause structure and integrity? **How can we redact only "veronica" from this raw String**?

### Solution

Lazily evaluate the the WHERE clause. In the above example, the ideal output would be...

```kotlin
"address LIKE '********'"
```

The redaction will be done in #147. This issue simply enables that. 

This will require us to refactor the `Where` class to hold a reference to the actual left-hand-side, operator, and right-hand-side values. Then lazily evaluate (combined) them when `toString` is invoked.

So, something like this...

```kotlin
data class Where<out T : Field> (
    private val lhs: LeftHandSide<T>,
    private val operator: Operator,
    private val rhs: RightHandSide<T>
) {

    private val evaluatedWhereString: String by unsafeLazy {
        "$lhs $operator $rhs"
    }

    override fun toString(): String = evaluatedWhereString
}

/**
 * Each element in a where statement has the structure; LHS OPERATOR RHS.
 *
 * The left hand side (lhs) can either be another where element OR it can be a field.
 */
internal sealed interface LeftHandSide<out T> {
    class WhereHolder<out T : Field>(val where: Where<T>) : LeftHandSide<T>
    class FieldHolder<out T : Field>(val field: T) : LeftHandSide<T>
}

/**
 * Each element in a where statement has the structure; LHS OPERATOR RHS.
 *
 * The right hand side (rhs) can either be another where element OR it can be any value.
 */
internal sealed interface RightHandSide<out T> {
    class WhereHolder<out T : Field>(val where: Where<T>) : RightHandSide<T>
    class ValueHolder<out T : Field>(val value: Any) : RightHandSide<T>
}

/**
 * Each element in a where statement has the structure; LHS OPERATOR RHS.
 *
 * The operator is an SQL operator.
 */
internal enum class Operator(val operator: String) {

    AND("AND"),
    OR("OR"),

    EQUAL("="),
    NOT_EQUAL("!="),

    GREATER_THAN(">"),
    GREATER_THAN_OR_EQUAL(">="),

    LESS_THAN("<"),
    LESS_THAN_OR_EQUAL("<="),

    IS("IS"),
    IS_NOT("IS NOT"),

    IN("IN"),
    NOT_IN("NOT IN"),

    LIKE("LIKE"),
    NOT_LIKE("NOT LIKE")
}
```

**Another benefit we get from this new structure** is that the type `T` is now actually used and retained to further enforce type safety 😁 This alone could have been a reason for this refactor 😎 There is also so much more that we can do when keep references to the typed properties.

### PR DESCRIPTION
**Pull request by vestrel00**
Most of the details are in #148. 

The gist of this change is that the intrinsic value an instance of `Where` is now lazily evaluated. Previously, `Where` only held a reference to the evaluated string. Now, it holds a reference to the left-hand-side, operator, and right-hand-side in a binary tree structure.

This will allow us to support things that need `Where` to be mutated, such as #148 and #142.

### CODE REVIEW

File: core/src/main/java/contacts/core/Where.kt [hunk 1]
```diff
@@ -403,108 +468,256 @@ private class RawContactsTableWhere(whereString: String) : Where<RawContactsFiel
...
  *
- * This is important because if the mimetypes are not paired with the query;
+ * The type [T] is not enforced within the class itself in order to support mutating functions
+ * such as [inRawContactsTable] and [inContactsTable]. This will allow us to construct a Where<X>
+ * from a Where<Y>.
  *
- * ```
- * WHERE (data1 = 'johnson' AND data1 = 'colorado')
- * ```
+ * ### Binary tree structure
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:496]: Oh boy! I happen to have built myself a binary tree 😁 Those interview leet code questions coming in to save the day!!!

File: core/src/main/java/contacts/core/Where.kt [hunk 2]
```diff
@@ -403,108 +468,256 @@ private class RawContactsTableWhere(whereString: String) : Where<RawContactsFiel
...
+ *                                 WhereHolder
+ *          WhereHolder                                    WhereHolder
+ *   FieldHolder  ValueHolder               WhereHolder                   WhereHolder
+ *                                   FieldHolder  ValueHolder       FieldHolder  ValueHolder
+ *
+ *  With this in mind, we can do some cool stuff like in [copyWithNewFieldType]!
  */
-private fun where(field: Field, operator: String, value: Any?, options: String? = null): String {
-    var where = "${field.columnName} $operator ${value.toSqlString()}"
+class Where<out T : Field> private constructor(
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:517]: The primary constructor is private. Two secondary constructors are exposed to ensure that the structure of the binary tree is upheld.

File: core/src/main/java/contacts/core/Where.kt [hunk 3]
```diff
@@ -403,108 +468,256 @@ private class RawContactsTableWhere(whereString: String) : Where<RawContactsFiel
...
+        return if (lhs is FieldHolder && rhs is ValueHolder) {
+            // Base case. Perform the substitution.
+            Where(
+                lhs = FieldHolder(substituteField(lhs.field)),
+                operator = operator,
+                rhs = rhs,
+                options = options
+            )
+        } else if (lhs is WhereHolder && rhs is WhereHolder) {
+            // Recursive case. Traverse tree.
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:583]: Who knew that recursion would actually come in handy once in a while 🤣

File: core/src/main/java/contacts/core/Where.kt [hunk 4]
```diff
@@ -403,108 +468,256 @@ private class RawContactsTableWhere(whereString: String) : Where<RawContactsFiel
...
+        }
     }
 
-    if (field is DataField && field.mimeType.value.isNotBlank()) {
-        where += " AND ${Fields.MimeType.columnName} = '${field.mimeType.value}'"
+    // Only evaluate this once to save some CPU. This assumes that property values are immutable.
+    // If there are mutable property values, then this will be evaluated at the time of invocation
+    // and will not mutate along with the mutable property values (e.g. a mutable list). I don't
+    // think consumers expect this to mutate anyways if they happen to save a reference to it.
+    private val evaluatedWhereString: String by unsafeLazy {
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:603]: Here is where the transformation into a string occurs. Should be self-explanatory 😁

File: core/src/main/java/contacts/core/Where.kt [hunk 5]
```diff
@@ -403,108 +468,256 @@ private class RawContactsTableWhere(whereString: String) : Where<RawContactsFiel
...
+
+        var whereString = when (operator) {
+            is Operator.Combine -> "($lhs) $operator ($rhs)"
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:606]: With the current structure, the `Combine` operators (AND, OR) imply that the `lhs` and `rhs` are both un-evaluated `Where`s. So, this is another for of recursion at play 😁
