### PR TITLE
Fixes #142 Query where 'and' operation with multiple data fields that have different mimetypes are not working

### LINKED ISSUE #142: Query where "and" operation with multiple data fields that have different mimetypes are not working
Code example:

Using filters:

Captura de pantalla 2021-12-21 a las 19 54 07

```
contacts
      .query()
      .where(filters whereAnd { it.isNotNullOrEmpty() })
      .include(
        Fields.Contact.Id,
        Fields.Contact.DisplayNamePrimary,
        Fields.Email.Address,
        Fields.Phone.Number,
        Fields.Address.FormattedAddress,
      )
.findWithContext()
```

It returns an empty list, and I have contacts with both, email and phone...

### PR DESCRIPTION
**Pull request by vestrel00**
When binary tree and recursion saves the day 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

The complete context for this work is in https://github.com/vestrel00/contacts-android/issues/142#issuecomment-1000948529

### CODE REVIEW

File: core/src/main/java/contacts/core/Query.kt [hunk 1]
```diff
@@ -582,7 +592,7 @@ private fun ContentResolver.resolve(
     // Get Contact Ids matching where from the Data table. If where is null, skip.
     if (where != null && !cancel()) {
         contactIds = mutableSetOf<Long>().apply {
-            addAll(findContactIdsInDataTable(where, cancel))
+            addAll(findContactIdsInDataTable(reduce(where, cancel), cancel))
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Query.kt:595]: Reduce the `where` such that one side of a "where AND where" will have zero mime type fields.

File: core/src/main/java/contacts/core/Query.kt [hunk 2]
```diff
@@ -676,14 +686,14 @@ internal fun ContentResolver.resolve(
...
-                RawContactsFields.Deleted notEqualTo true
-           },
+                    if (contactIds != null) {
+                        // Note that we do not need to check for the DELETED flag here because RawContacts
+                        // that are marked for deletion also have a null Contact ID reference.
+                        RawContactsFields.ContactId `in` contactIds
+                    } else {
+                        // There may be RawContacts that are marked for deletion that have not yet been deleted.
+                        RawContactsFields.Deleted notEqualTo true
+                    },
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Query.kt:696]: Indentation fixes by Android Studio. No real changes here.

File: core/src/main/java/contacts/core/Query.kt [hunk 3]
```diff
@@ -694,45 +704,51 @@ internal fun ContentResolver.resolve(
...
     contactsWhere: Where<ContactsField>?, cancel: () -> Boolean, suppressDbExceptions: Boolean
-): Set<Long> = query(
-    Table.Contacts, Include(ContactsFields.Id), contactsWhere,
-    suppressDbExceptions = suppressDbExceptions
-) {
-    mutableSetOf<Long>().apply {
-        val contactsCursor = it.contactsCursor()
-        while (!cancel() && it.moveToNext()) {
-            add(contactsCursor.contactId)
+): Set<Long> = if (cancel()) emptySet() else {
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Query.kt:707]: Check if cancelled immediately.

File: core/src/main/java/contacts/core/Query.kt [hunk 4]
```diff
@@ -694,45 +704,51 @@ internal fun ContentResolver.resolve(
...
-    Include(RawContactsFields.ContactId),
-    // There may be RawContacts that are marked for deletion that have not yet been deleted.
-    (RawContactsFields.Deleted notEqualTo true) and rawContactsWhere,
-    suppressDbExceptions = suppressDbExceptions
-) {
-    mutableSetOf<Long>().apply {
-        val rawContactsCursor = it.rawContactsCursor()
-        while (!cancel() && it.moveToNext()) {
-            add(rawContactsCursor.contactId)
+): Set<Long> = if (cancel()) emptySet() else {
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Query.kt:723]: Check if cancelled immediately.

File: core/src/main/java/contacts/core/Query.kt [hunk 5]
```diff
@@ -694,45 +704,51 @@ internal fun ContentResolver.resolve(
...
     where: Where<AbstractDataField>?, cancel: () -> Boolean
-): Set<Long> = query(Table.Data, Include(Fields.Contact.Id), where) {
-    val contactIds = mutableSetOf<Long>()
-    val contactsCursor = it.dataContactsCursor()
-    while (!cancel() && it.moveToNext()) {
-        contactIds.add(contactsCursor.contactId)
-    }
-    contactIds
-} ?: emptySet()
+): Set<Long> = if (cancel()) emptySet() else {
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Query.kt:742]: Immediately check if cancelled.

File: core/src/main/java/contacts/core/Where.kt [hunk 6]
```diff
@@ -501,49 +502,6 @@ private fun <F : Field, V : Any?> Sequence<V>.combineWhere(
 
 // endregion
 
-// region Conversions
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:504]: Moved to `WhereSubstitutions.kt` file.

File: core/src/main/java/contacts/core/Where.kt [hunk 7]
```diff
@@ -582,119 +540,75 @@ internal fun <T : AbstractDataField> Where<T>.inRawContactsTable(): Where<RawCon
  *  With this in mind, we can do some cool stuff like in [copyWithNewFieldType]!
  */
 class Where<out T : Field> private constructor(
-    private val lhs: LeftHandSide,
-    private val operator: Operator,
-    private val rhs: RightHandSide,
+    internal val lhs: LeftHandSide,
+    internal val operator: Operator,
+    internal val rhs: RightHandSide,
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:545]: Had to make these internal to avoid having to write long functions inside this class.

File: core/src/main/java/contacts/core/Where.kt [hunk 8]
```diff
@@ -582,119 +540,75 @@ internal fun <T : AbstractDataField> Where<T>.inRawContactsTable(): Where<RawCon
...
     /**
-     * Returns a copy of this [Where] such that LHS fields are substituted with the output of
-     * [substituteField] and RHS values are substituted with the output of [substituteValue].
+     * Returns the [MimeType]s of all of the fields (for wheres in the form of "field match value")
+     * in this where tree.
+     *
+     * The order of traversal is preorder (this, lhs, rhs). The first mimeType in the list will be
+     * the mimeType of this (if it holds a field).
      */
-    private fun <R : Field> copyWithFieldValueSubstitutions(
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:649]: Moved to `WhereSubstitutions.kt` file.

File: core/src/main/java/contacts/core/Where.kt [hunk 9]
```diff
@@ -582,119 +540,75 @@ internal fun <T : AbstractDataField> Where<T>.inRawContactsTable(): Where<RawCon
...
-                ),
-                options = options
-            )
-        } else {
-            // This should not happen with the current structure. If this does happen, it means
-            // that we made some changes that broke the structure.
-            throw ContactsException(
-                "Unhandled Where form lhs: ${lhs.javaClass.simpleName}, rhs: ${rhs.javaClass.simpleName}"
-            )
+    internal val mimeTypes: Set<MimeType> by unsafeLazy {
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/Where.kt:598]: Returns all of the different mimeTypes used in this where and its descendants.

File: core/src/main/java/contacts/core/data/DataQuery.kt [hunk 10]
```diff
@@ -94,7 +94,7 @@ interface DataQueryFactory {
 }
 
 @Suppress("FunctionName")
-internal fun DataQuery(contacts: Contacts, isProfile: Boolean): DataQueryFactory =
+internal fun DataQueryFactory(contacts: Contacts, isProfile: Boolean): DataQueryFactory =
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/data/DataQuery.kt:97]: I noticed that this function did not have the correct name so I corrected it. Just boyscouting =)

File: core/src/main/java/contacts/core/entities/Entity.kt [hunk 11]
```diff
@@ -199,11 +199,6 @@ internal fun Any?.isNotNullOrBlank(): Boolean = when (this) {
     else -> true
 }
 
-// TODO migrate all of the below functions to use all, any, none and add documentation
-// https://play.kotlinlang.org/byExample/05_Collections/05_existential
-// Make some temporary tests to ensure the new function versions match the output of the old.
-// Make sure to test the case where the list is empty!!!
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/entities/Entity.kt:205]: I already did this.

File: core/src/main/java/contacts/core/util/WhereSubstitutions.kt [hunk 12]
```diff
@@ -0,0 +1,269 @@
...
+ *
+ * More specifically, this translates the following column names to work with the Contacts table;
+ *
+ * - RawContacts.CONTACT_ID -> Contacts._ID
+ * - Data.CONTACT_ID -> Contacts._ID
+ *
+ * This does no translate anything else. So any fields used that does not exist in the Contacts
+ * table will remain.
+ */
+internal fun Where<AbstractDataField>.inContactsTable(): Where<ContactsField> =
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/util/WhereSubstitutions.kt:17]: Moved. No changes.

File: core/src/main/java/contacts/core/util/WhereSubstitutions.kt [hunk 13]
```diff
@@ -0,0 +1,269 @@
...
+ * Converts [this] Data where clause to a where clause that is usable for the RawContacts table.
+ *
+ * More specifically, this translates the following column names to work with the RawContacts table;
+ *
+ * - Data.RAW_CONTACT_ID -> RawContacts._ID
+ *
+ * This does no translate anything else. So any fields used that does not exist in the RawContacts
+ * table will remain.
+ */
+internal fun Where<AbstractDataField>.inRawContactsTable(): Where<RawContactsField> =
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/util/WhereSubstitutions.kt:39]: Moved. No changes.

File: core/src/main/java/contacts/core/util/WhereSubstitutions.kt [hunk 14]
```diff
@@ -0,0 +1,269 @@
...
+        }
+    )
+
+/**
+ * Returns a copy of this [Where] such that LHS fields are substituted with the output of
+ * [substituteField] and RHS values are substituted with the output of [substituteValue].
+ *
+ * This also allows for mutating the type [T] to any type [R].
+ */
+internal fun <T : Field, R : Field> Where<T>.copyWithFieldValueSubstitutions(
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/util/WhereSubstitutions.kt:55]: Moved. No changes.

File: core/src/main/java/contacts/core/util/WhereSubstitutions.kt [hunk 15]
```diff
@@ -0,0 +1,269 @@
...
+ *
+ * where  -> (Email or Phone) and (Organization or Website)
+ * reduce -> (ContactIDs) and (Organization or Website)
+ *
+ * The idea is to reduce the amount of mimetype-aware matches such that there is 0 mimetype-aware
+ * match in one side of the AND.
+ *
+ * More context in https://github.com/vestrel00/contacts-android/issues/142#issuecomment-1000948529
+ */
+internal fun ContentResolver.reduce(
```
Comment (vestrel00) [inline core/src/main/java/contacts/core/util/WhereSubstitutions.kt:163]: This is where the magic happens. I'll let the documentation and code speak for themselves ❤️
