### PR TITLE
(Closes #291) Adjust EventData.fromDateStrFromDb to handle index-out-of-bounds exce…

### LINKED ISSUE #291: ArrayIndexOutOfBoundsException when querying contacts (and Fields.Event.Date is included)
Encountering a crash (note: our app is still on 0.2.4) that I have yet to be able to reproduce but crash logs have come in from several users over the past month. (We have low-urgency to resolve this at the moment.) Here is the relevant stack trace:
```
Exception java.lang.ArrayIndexOutOfBoundsException: length=13; index=18
  at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate (BaseCalendar.java:453)
  at java.util.GregorianCalendar.computeFields (GregorianCalendar.java:2408)
  at java.util.GregorianCalendar.computeTime (GregorianCalendar.java:2810)
  at java.util.Calendar.updateTime (Calendar.java:3403)
  at java.util.Calendar.getTimeInMillis (Calendar.java:1761)
  at java.util.Calendar.getTime (Calendar.java:1734)
  at java.text.SimpleDateFormat.parseInternal (SimpleDateFormat.java:1857)
  at java.text.SimpleDateFormat.parse (SimpleDateFormat.java:1755)
  at java.text.DateFormat.parse (DateFormat.java:387)
  at contacts.core.entities.EventDate$Companion.fromDateStrFromDb$core_release (EventDate.java:13)
  at contacts.core.entities.mapper.EventMapper.getValue (EventMapper.java:13)
  at contacts.core.entities.mapper.EventMapper.getValue (EventMapper.java:13)
  at contacts.core.entities.mapper.EntityMapper$DefaultImpls.getNonBlankValueOrNull (EntityMapper.java:1)
  at contacts.core.entities.mapper.DataEntityMapper$DefaultImpls.getNonBlankValueOrNull (DataEntityMapper.java:1)
  at contacts.core.entities.mapper.EventMapper.getNonBlankValueOrNull (EventMapper.java:2)
  at contacts.core.entities.mapper.EventMapper.getNonBlankValueOrNull (EventMapper.java:2)
  at contacts.core.entities.mapper.ContactsMapperKt.updateRawContact (ContactsMapper.kt:90)
  at contacts.core.entities.mapper.ContactsMapperKt.access$updateRawContact (ContactsMapper.kt:90)
  at contacts.core.entities.mapper.ContactsMapper.processDataCursor (ContactsMapper.kt:90)
  at contacts.core.QueryKt.resolve (Query.kt:90)
  at contacts.core.QueryKt.resolve (Query.kt:36)
  at contacts.core.QueryKt.access$resolve (Query.kt:36)
  at contacts.core.QueryImpl.find (QueryImpl.java:36)
  at contacts.core.QueryImpl.find (QueryImpl.java:36)
```

Note that the `index` value varies across crash logs; also have seen -24 and -7.

I see that fromDateStrFromDb try/catches for a ParseException but not an ArrayIndexOutOfBoundsException.

Our query code looks like
```
val contacts = Contacts(context)
    .query()
    .find()
```

Since we don't need any event fields, I wonder if we could avoid this entirely by only specifying the fields we need:
```
val contacts = Contacts(context)
    .query()
    .include {
        setOf(
            Contact.Id,
            Contact.DisplayNamePrimary,
            Phone.Number,
            Phone.NormalizedNumber
        )
    }
    .find()
```

Or do you think the crash would still occur? Thanks!

### PR DESCRIPTION
**Pull request by salami**
…ptions in case SimpleDateFormat throws it during parsing of date

#291

### CODE REVIEW

File: core/src/main/java/contacts/core/entities/Event.kt [hunk 1]
```diff
@@ -309,6 +309,8 @@ data class EventDate internal constructor(
                 }
             } catch (pe: ParseException) {
                 null
+            } catch (e: IndexOutOfBoundsException) {
+                null
             }
```
Comment (salami) [inline core/src/main/java/contacts/core/entities/Event.kt:314]: Or we could just catch any Exception to make things simpler?

Comment (vestrel00) [reply core/src/main/java/contacts/core/entities/Event.kt:314]: This should be fine for now. If we start to see other exceptions in the future, then we can think about coalescing it into just exception.

**Review by vestrel00 — APPROVED** [review]
Nice. Thanks so much for finding and raising the issue and then making the fix!!
